steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Lint
  - name: python
    entrypoint: python
    args: ["-m", "pylint", "--disable=R,C", "app.py"]

  # Run unit tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "-vv", "--cov=hello", "test_hello.py", "--junitxml=${SHORT_SHA}_test_log.xml"]

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}/mlops:${SHORT_SHA}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}/mlops:${SHORT_SHA}']

# Save test logs to Google Cloud Storage
artifacts:
  objects:
    location: gs://pierre-test/mlops/build-logs/
    paths:
      - ${SHORT_SHA}_test_log.xml
# Store images in Google Artifact Registry
images:
  - eu.gcr.io/${PROJECT_ID}/${REPO_NAME}/mlops:${SHORT_SHA}